package Kotlin

object Contact {
    fun getAllAbrrevation(): List<Abrrevation> {
        return listOf(
            Abrrevation("a","arab tiliga mansub so’z"),
            Abrrevation("avia","aviatsiyaga oid termin"),
            Abrrevation("ad","adabiyotga, adabiyotshunoslikka oid termin"),
            Abrrevation("ayn","aynan"),
            Abrrevation("ayr.bog’l","ayiruvchi bog’lovchi"),
            Abrrevation("ayr.yukl","ayiruv yuklamasi"),
            Abrrevation("anat","anatomiyaga oid termin"),
            Abrrevation("arxeol","arxeologiyaga oid termin"),
            Abrrevation("arxit","arxitekturaga oid termin "),
            Abrrevation("astr","astronomiyaga oid termin"),
            Abrrevation("afrikaans","afrikaans (bur) tiliga mansub so’z"),
            Abrrevation("belg.olm","belgilash olmoshi"),
            Abrrevation("betklf","mensimaslikni ifodalovchi yoki betakalluf muomalada qo’llanuvchi so’z, ibora"),
            Abrrevation("biol","biologiyaga oid termin"),
            Abrrevation("birg.n","birgalik nisbati"),
            Abrrevation("birl","birlik son"),
            Abrrevation("b.k.","bosh kelishik"),
            Abrrevation("bnk","binokorlikka oid termin"),
            Abrrevation("bol","bolalar nutqiga xos, bolalar ishlatadigan so’z"),
            Abrrevation("bot","botanikaga oid termin"),
            Abrrevation("bog'","bog’dorchilikka oid termin"),
            Abrrevation("bog’l","bog’lovchi"),
            Abrrevation("brkt. bog’l","biriktiruvchi bog’lovchi"),
            Abrrevation("buyr.m","buyruq mayli"),
            Abrrevation("buxg","buxgalteriyaga, hisob-kitobga oid termin"),
            Abrrevation("va b","va boshqa(lar)"),
            Abrrevation("va sh.k","va shu kabi(lar)"),
            Abrrevation("veng","venger tiliga mansub so’z"),
            Abrrevation("vet","veterinariyaga oid termin"),
            Abrrevation("vzf","(Biror so’z, gap bo'lagi) vazifasida "),
            Abrrevation("g","gramm"),
            Abrrevation("geogr","geografiyaga oid termin"),
            Abrrevation("geod","geodeziyaga oid termin"),
            Abrrevation("geol","geologiyaga oid termin "),
            Abrrevation("geom","geometriyaga oid termin "),
            Abrrevation("geofiz","geofizikaga oid termin"),
            Abrrevation("gidr","gidrologiyaga, gidrotexnikaga oid termin"),
            Abrrevation("goll","golland tiliga mansub so’z "),
            Abrrevation("gruz","gruzin tiliga mansub so’z "),
            Abrrevation("gum.olm","gumon olmoshi"),
            Abrrevation("dag’l","dag’al, qo’pol so’z, ibora "),
            Abrrevation("deng","dengizchilikka oid termin "),
            Abrrevation("din","diniy so’z, ibora "),
            Abrrevation("dip","diplomatiyaga oid termin "),
            Abrrevation("yord.fl","yordamchi fe’l"),
            Abrrevation("jaml.son ","jamlovchi son "),
            Abrrevation("jarg","jargon so’z, ibora "),
            Abrrevation("j.k","jo’nalish kelishigi "),
            Abrrevation("zid","(Biror so’z, iboraning) ziddi, antonimi"),
            Abrrevation("zidl.bog’l","zidlovchi bog’lovchi"),
            Abrrevation("zool","zoologiyaga oid termin "),
            Abrrevation("ingl","ingliz tiliga mansub so’z "),
            Abrrevation("indeys","indeys tillariga mansub so’z "),
            Abrrevation("isl","island tiliga mansub so’z "),
            Abrrevation("isp","ispan tiliga mansub so’z"),
            Abrrevation("ital","italyan tiliga mansub so’z"),
            Abrrevation("iqt","iqtisodiyotga oid termin"),
            Abrrevation("y","yil"),
            Abrrevation("kam qo'll","kam qo’llanadigan so’z, ibora "),
            Abrrevation("kams","kamsitishni ifodalovchi so’z, ibora"),
            Abrrevation("kart","karta o’yiniga oid so’z, ibora"),
            Abrrevation("kg","kilogramm"),
            Abrrevation("kel.zam","fe’lning kelasi zamon shakli "),
            Abrrevation("kest","kesatik, kinoya anglatadigan so’z, ibora"),
            Abrrevation("kim","kimyoga oid termin"),
            Abrrevation("kino","kinematografiyaga oid termin"),
            Abrrevation("kichr","kichraytish shakli"),
            Abrrevation("km","kilometr"),
            Abrrevation("kon","konchilikka oid termin"),
            Abrrevation("krsh.s","kirish so’z"),
            Abrrevation("kt","kitobiy so’z, ibora"),
            Abrrevation("ksh.olm","kishilik olmoshi"),
            Abrrevation("kul","kulinariyaga, oshpazlikka oid termin "),
            Abrrevation("kuch","kuchaytirish shakli"),
            Abrrevation("kuch.yukl","kuchaytiruv yuklamasi"),
            Abrrevation("ko'm","ko’makchi"),
            Abrrevation("ko'm.fl","ko'makchi fe’l"),
            Abrrevation("ko'pl","ko’plik son"),
            Abrrevation("ko'rs.olm","ko’rsatish olmoshi"),
            Abrrevation("ko'chma","ko’chma ma’noda, ko’chma ma’nosi "),
            Abrrevation("l","litr"),
            Abrrevation("l.m","lug’aviy ma’nosi"),
            Abrrevation("lot","lotin tiliga mansub so’z"),
            Abrrevation("m","metr"),
            Abrrevation("mavh.ot","mavhum ot"),
            Abrrevation("majh.n","majhul nisbat"),
            Abrrevation("malyachcha","malayya tiliga mansub so’z"),
            Abrrevation("mas","masalan"),
            Abrrevation("mat","matematikaga oid termin"),
            Abrrevation("maxs","maxsus so’z, termin"),
            Abrrevation("mg","milligramm"),
            Abrrevation("meteor","meteorologiyaga oid termin "),
            Abrrevation("mex","mexanikaga oid termin"),
            Abrrevation("min","mineralogiyaga oid termin"),
            Abrrevation("mif","mifologiyaga oid termin"),
            Abrrevation("ml","moliyaga oid termin"),
            Abrrevation("mln","million"),
            Abrrevation("mm","millimetr"),
            Abrrevation("mnt","mantiqqa oid termin "),
            Abrrevation("mod.s","modal so’z"),
            Abrrevation("mtr","metrologiyaga oid termin"),
            Abrrevation("mus","musiqaga, musikashunoslikka oid termin"),
            Abrrevation("mug'l","mug’ul tiliga mansub so’z "),
            Abrrevation("n","nisbat (fe'l nisbat"),
            Abrrevation("nazm","nazmda ishlatiladigan so’z, ibora "),
            Abrrevation("nafr","nafrat, jirkanish anglatadigan so’z, ibora"),
            Abrrevation("nem","nemis tiliga mansub so’z"),
            Abrrevation("neol","neologizm, yangi so’z"),
            Abrrevation("ov","ovchilikka oid termin"),
            Abrrevation("olm","olmosh"),
            Abrrevation("opt","optikaga oid termin"),
            Abrrevation("ort.n","orttirma nisbat"),
            Abrrevation("palnt","paleontologiyaga oid termin"),
            Abrrevation("ped","pedagogikaga oid termin"),
            Abrrevation("plgrf","poligrafiyaga oid termin"),
            Abrrevation("pol","polyak tiliga mansub so’z"),
            Abrrevation("port","portugal tiliga mansub so’z"),
            Abrrevation("poet","poetik so’z, poeziyada, nazmda ishlatiladigan so’z, ibora"),
            Abrrevation("psxl","psixologiyaga oid termin"),
            Abrrevation("r","rus tiliga mansub"),
            Abrrevation("radio","radiotexnikaga oid termin "),
            Abrrevation("rasm","rasmiy uslubda qo’llanadigan so’z, ibora"),
            Abrrevation("rvdsh","ravishdosh"),
            Abrrevation("rvsh","ravish"),
            Abrrevation("rum","rumin tiliga mansub so’z"),
            Abrrevation("s","so'z"),
            Abrrevation("salb","salbiy ma’noni ifodalovchi so’z, ibora"),
            Abrrevation("sansk","sanskrit tiliga mansub so’z"),
            Abrrevation("siyos","siyosatga, siyosatshunoslikka oid termin"),
            Abrrevation("skand","skandinav tillariga mansub so’z "),
            Abrrevation("stn","san’atga oid termin"),
            Abrrevation("snq.s","sanoq son"),
            Abrrevation("sprt","sport va fizkulturaga oid termin "),
            Abrrevation("s.t","so’zlashuv tilida (og’zaki nutqda) qo’llanadigan so’z, ibora"),
            Abrrevation("sug'd","sug’d tiliga mansub so’z"),
            Abrrevation("sfdsh","sifatdosh"),
            Abrrevation("sft","sifat"),
            Abrrevation("so'k","sukish yoki koyishni ifodalaydigan so’z, ibora"),
            Abrrevation("sur.olm","suroq olmoshi"),
            Abrrevation("sur.yukl","suroq yuklamasi"),
            Abrrevation("t","turkiy, umumturkiy so’z"),
            Abrrevation("takr.s","takroriy so’z"),
            Abrrevation("tar","tarixga oid, tarixiy termin"),
            Abrrevation("tasv.s","tasviriy so’z"),
            Abrrevation("tat","tatar tiliga mansub so’z"),
            Abrrevation("taql.s","taklid so’z"),
            Abrrevation("taqs.s","taqsim son"),
            Abrrevation("teatr","teatrga oid termin"),
            Abrrevation("tex","texnikaga oid termin"),
            Abrrevation("tib","tibbiyotga oid termin "),
            Abrrevation("tij","tijoratga, kommersiyaga oid termin "),
            Abrrevation("t.y","temir yo'lga oid termin"),
            Abrrevation("t.k","tushum kelishigi"),
            Abrrevation("tlsh","tilshunoslikka oid termin"),
            Abrrevation("top","topografiyaga oid termin"),
            Abrrevation("trns","transportga oid termin"),
            Abrrevation("trtb.s","tartib son"),
            Abrrevation("turk","turk tiliga mansub"),
            Abrrevation("to'qm","to’qimachilikka oid termin"),
            Abrrevation("ukr","ukrain tiliga mansub so’z "),
            Abrrevation("und.s","undov so’z"),
            Abrrevation("f","fors va tojik tillariga mansub so’z "),
            Abrrevation("farm","farmatsevtikaga, farmakologiyaga oid termin"),
            Abrrevation("fiz","fizikaga oid termin"),
            Abrrevation("fiziol","fiziologiyaga oid termin"),
            Abrrevation("fin","fin tiliga mansub so’z"),
            Abrrevation("fl","fe'l"),
            Abrrevation("fls","falsafaga oid termin"),
            Abrrevation("folk","folklorga oid so’z"),
            Abrrevation("foto","fotografiyaga oid termin"),
            Abrrevation("fr","fransuz tiliga mansub so’z"),
            Abrrevation("xit","xitoy tiliga mansub so’z"),
            Abrrevation("x-u","xotin-qizlar nutsiga xos,xotin-qizlar nutqida ishlatiladigan so’z, ibora"),
            Abrrevation("ch.k","chiqish kelishigi"),
            Abrrevation("sh","shaxs"),
            Abrrevation("shaxm","shaxmatga oid termin"),
            Abrrevation("shv","shevaga oid so’z, ibora"),
            Abrrevation("sh.k","shu kabi(lar)"),
            Abrrevation("eg.olm","egalik olmoshi"),
            Abrrevation("el","elektrga, elektrotexnikaga oid termin "),
            Abrrevation("erg.bog'l","ergashtiruvchi bog’lovchi"),
            Abrrevation("erkl","erkalashni ifodalaydigan so’z, ibora"),
            Abrrevation("esk","eskirgan so’z, ibora"),
            Abrrevation("eti","etnografiyaga oid termin"),
            Abrrevation("yukl","yuklama"),
            Abrrevation("yun","yunon (grek) tiliga mansub so’z"),
            Abrrevation("yuq.usl","yuqori uslub"),
            Abrrevation("yap","yapon tiliga mansub so’z"),
            Abrrevation("o'zl.n","o'zlik nisbati"),
            Abrrevation("o'zl.olm","o'zlik olmoshi"),
            Abrrevation("o'- p.k","o’rin-payt kelishigi"),
            Abrrevation("o'tg.zam","fe’lning o’tgan zamon shakli"),
            Abrrevation("q","qarang"),
            Abrrevation("qad.r","qadimgi rus tiliga mansub so’z"),
            Abrrevation("qad.yah","qadimgi yahudiy tiliga mansub so’z"),
            Abrrevation("qarg'","qarg’ish so’zi, iborasi"),
            Abrrevation("q.k","qaratqich kelishigi"),
            Abrrevation("q.x","qishloq xo’jaligiga oid termin"),
            Abrrevation("g'alat","noto’g’ri ishlatilgan (yozilgan) so’z"),
            Abrrevation("hazil","hazil qilib aytilgan so’z, ibora"),
            Abrrevation("harb","harbiy ishga oid so’z, termin"),
            Abrrevation("har.n","harakat nomi"),
            Abrrevation("haqr","haqorat ifodalaydigan so’z, ibora"),
            Abrrevation("hind","hind tiliga mansub so’z"),
            Abrrevation("hoz.zam","fe’lning hozirgi zamon shakli"),
            Abrrevation("huq","huquqqa, huquqshunoslikka oid termin")
        )
    }
}